### ISSUE TITLE
Does not work with (lazy-loaded) engines

### ISSUE THREAD

**Issue by buschtoens** [ember-polyfills/ember-angle-bracket-invocation-polyfill#47]
Only tested this with a lazy-loaded engine, but I would assume that eagerly bundled engines are also affected.

Since the runtime polyfill only patches the [`buildRegistry` method](https://github.com/emberjs/ember.js/blob/v3.4.1/packages/%40ember/application/lib/application.js#L1062) of the [`Application` class](https://www.emberjs.com/api/ember/3.4/classes/Application), it has no effect on engines:

https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill/blob/53afc725e13d8db63bf8006c0c906969441482de/vendor/angle-bracket-invocation-polyfill/runtime-polyfill.js#L57-L60

Which is why it causes this error:

```
Uncaught Error: Assertion Failed: You cannot use 'SomeComponent' as a component name. Component names must contain a hyphen
```

I understand that `Application` extends [`Engine`](https://www.emberjs.com/api/ember/3.4/classes/Engine), but that this polyfill has to patch `Application` instead of `Engine`, because it needs to override some registry entries only defined in `Application`:

https://github.com/emberjs/ember.js/blob/v3.4.1/packages/%40ember/application/lib/application.js#L1091-L1093

I now tried running the same polyfill for `Engine` _in addition_ to `Application` and so far it seems to work. 🤷‍♂️ 

This is not ideal for `Application` though, because the polyfill is:

- registered in `Engine`
- then overridden in `Application`
- and then registered again in `Application`

Do you still think that this is a valid solution going forward? I will submit a PR then.

**Comment by rwjblue** [comment]
Definitely seems like a reasonable start, happy to help tweak it in a PR...

**Comment by jbailey4** [comment]
My team recently ran into this as well when creating a new engine within our older application at ember@2.18.2. We wanted to install this as a way to start using some of the newer ember syntax, since it was a greenfield project.

Happy to help with anything needed to get this fix in!

**Comment by rwjblue** [comment]
https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill/pull/48 seems to have stalled a bit, any folks looking for this functionality willing to pick it up?
